language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nitinsimps/docker-nit -f Dockerfile.dev .

script:
  - docker run -e CI=true nitinsimps/docker-nit npm run test